# Generated by Django 5.0.7 on 2024-08-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='welcome_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('count', models.CharField(default='0', max_length=3)),
            ],
        ),
    ]
