# Generated by Django 5.0.7 on 2024-08-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic')),
                ('name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('rate', models.IntegerField(max_length=20)),
                ('Booking_Closes_on', models.DateField()),
            ],
        ),
    ]
