# Generated by Django 5.0.7 on 2024-08-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
