# Generated by Django 5.0.7 on 2024-09-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_tickets_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='Date',
            new_name='event_date',
        ),
    ]
