# Generated by Django 5.0.7 on 2024-09-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_name_events_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event',
            new_name='name',
        ),
    ]
