# Generated by Django 5.0.7 on 2024-09-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_tickets_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tickets_count',
            new_name='no_of_tickets',
        ),
    ]
