# Generated by Django 5.0.7 on 2024-09-01 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_name_booking_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='event',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
