# Generated by Django 5.0.7 on 2024-09-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_pending_cancellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pending_cancellation',
        ),
    ]
