# Generated by Django 5.0.7 on 2024-09-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_pending_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_tickets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
